export const Manner = {
  1: "Ingratiating and cloying",
  2: "Grimly suspicious of the PCs or their backers",
  3: "Having a xenophlic interest in the novelty of the PCs",
  4: "Pragmatic and businesslike",
  5: "Romantically interested in one or more PCs",
  6: "A slimy used-gravcar dealer’s approach",
  7: "Wide-eyed awe at the PCs",
  8: "A cool and superior attitude toward PC 'hirelings'",
  9: "Benevolently patronizing toward outsiders",
  10: "Sweaty-palmed need or desperation",
  11: "Xenophobic mistrust of the PCs",
  12: "Idealistic enthusiasm for a potentially shared cause",
  13: "Somewhat intoxicated by recent indulgence",
  14: "Smoothly persuasive and reasonable",
  15: "Visibly uncomfortbale with the PCs",
  16: "Grossly overconfident in PC abilities",
  17: "Somewhat frightened by the PCs",
  18: "Deeply misunderstanding of the PCs’ culture",
  19: "Extremely well-informed about the PCs’ past",
  20: "Distracted by their current situation",
}
export const Outcome = {
  1: "They’ll screw the PCs over even at their own cost",
  2: "They firmly intend to actively betray the PCs",
  3: "They won't keep the deal unless driven to it",
  4: "They plan to twist the deal to their own advantage",
  5: "They won't keep their word unless it's profitable",
  6: "They’ll flinch from paying up when the time comes",
  7: "They mean to keep the deal, but are reluctant",
  8: "They’ll keep most of the deal, but not all of it",
  9: "They'll keep the deal slowly and grudgingly",
  10: "They’ll keep the deal but won’t go out of their way",
  11: "They'll be reasonably punctual about the deal",
  12: "They’ll want a further small favor to pay up on it",
  13: "They'll keep the deal in a way that helps them",
  14: "They’ll keep the deal if it’s still good for them",
  15: "They'll offer a bonus for an additional favor",
  16: "They're trustworthy as long as the deal won’t hurt them",
  17: "They're trustworthy with the NPC following through",
  18: "They’ll be very fair in keeping to their agreements",
  19: "They'll keep bargains even at their own cost",
  20: "They have complete and righteous integrity to the bitter end",
}
export const Motivation = {
  1: "An ambition for greater social status",
  2: "Greed for wealth and indulgent riches",
  3: "To protect a loved one who is somehow imperiled",
  4: "A sheer sadistic love of inflicting pain and suffering",
  5: "A hedonistic enjoyment of pleasing company",
  6: "Searching out hidden knowledge or science",
  7: "Establishing or promoting a cultural institution",
  8: "Avenging a grievous wrong to them or a loved one",
  9: "Promoting their religion and living out their faith",
  10: "Winning the love of a particular person",
  11: "Winning glory and fame in their profession",
  12: "Dodging an enemy who is pursuing them",
  13: "Driving out or killing an enemy group",
  14: "Deposing a rival to them in their line of work",
  15: "Getting away from this world or society",
  16: "Promote a friend or offspring’s career or future",
  17: "Taking control of a property or a piece of land",
  18: "Building a structure or a complex prototype tech",
  19: "Performing or creating their art to vast acclaim",
  20: "To redeem themselves from a prior failure",
}
export const Want = {
  1: "Bring them an exotic piece of tech",
  2: "Convince someone to meet with the NPC",
  3: "Kill a particular NPC",
  4: "Kidnap or non-fatally eliminate a particular NPC",
  5: "Pay them a large amount of money",
  6: "Take a message to someone hard to reach",
  7: "Acquire a tech component that's hard to get",
  8: "Find proof of a particular NPC’s malfeasance",
  9: "Locate a missing NPC",
  10: "Bring someone to a destination via dangerous travel",
  11: "Retrieve a lost or stolen object",
  12: "Defend someone from an impending attack",
  13: "Burn down or destroy a particular structure",
  14: "Explore a dangerous or remote location",
  15: "Steal something from a rival NPC or group",
  16: "Intimidate a rival into ceasing their course of action",
  17: "Commit a minor crime to aid the NPC",
  18: "Trick a rival into doing something",
  19: "Rescue an NPC from a dire situation",
  20: "Force a person or group to leave an area",
}
export const Power = {
  1: "They’re just really appealing and sympathetic to PCs",
  2: "They have considerable liquid funds",
  3: "They control the use of large amounts of violence",
  4: "They have a position of great social status",
  5: "They're a good friend of an important local leader",
  6: "They have blackmail info on the PCs",
  7: "They have considerable legal influence here",
  8: "They have tech the PCs might reasonably want",
  9: "They can get the PCs into a place they want to go",
  10: "They know where significant wealth can be found",
  11: "They have information about the PCs current goal",
  12: "An NPC the PCs need has implicit trust in them",
  13: "The NPC can threaten someone the PCs like",
  14: "They control a business relevant to PC needs",
  15: "They have considerable criminal contacts",
  16: "They have pull with the local religion",
  17: "They know a great many corrupt politicians",
  18: "They can alert the PCs to an unexpected peril",
  19: "They’re able to push a goal the PCs currently have",
  20: "They can get the PCs useful permits and rights",
}

export const Hook = {
  1: "have a particular odd style of dress",
  2: "have an amputation or other maiming",
  3: "have visible cyberware or prosthetics",
  4: "have unusual hair, skin, or eye colors",
  5: "have scarring, either intentional or from old injuries",
  6: "have a tic-like overuse of a particular word or phrase",
  7: "have a specific unusual fragrance or cologne",
  8: "are constantly fiddling with a particular item",
  9: "have visible signs of drug use",
  10: "always seem to be in one particular mood",
  11: "Wear badges or marks of allegiance to a cause",
  12: "have an extremely slow or fast pace of speech",
  13: "Wheeze, shake, or some other signs of infirmity",
  14: "Constantly have a drink to hand",
  15: "are always complaining about a group or organization",
  16: "are paranoid, possibly for justifiable reasons",
  17: "insist on a particular location for all meetings",
  18: "Communicate strictly through a third party",
  19: "are abnormally obese, emaciated, tall, or short",
  20: "are always found with henchmen or friends",
}